when normal make fails but there is a template with that target, try the template.

diff --git a/src/bin/mzke b/src/bin/mzke
--- a/src/bin/mzke
+++ b/src/bin/mzke
@@ -2,7 +2,7 @@
 
 # mzke -- ZDS make wrapper
 
-MZKE_VERSION=0.1.1-20260210
+MZKE_VERSION=0.1.1-20260215
 MZKE_ROOT=/usr/local/share/mzke
 
 [[ "$1" == --version || "$1" == -v ]] && echo mzke version $MZKE_VERSION && make --version && exit 0
@@ -90,3 +90,14 @@ fi
 # Execute make
 [[ "$NO_PRINT_BANNER" == 1 ]] || echo make -f $MAKEFILE $SUBDIR $OPTS $VARS $ARGS_QUOTED $TARGET
 eval make -f \"$MAKEFILE\" $SUBDIR $OPTS $VARS $ARGS_QUOTED $TARGET
+err_num=$?
+
+# make failed but there is a template?  try that.
+if [[ "$err_num" -eq 2 && -n "$TARGET" && -f "$MZKE_ROOT/templates/Mzkefile.$TARGET.mk" ]]; then
+  MAKEFILE="$MZKE_ROOT/templates/Mzkefile.$TARGET.mk"
+  [[ "$NO_PRINT_BANNER" == 1 ]] || echo make -f $MAKEFILE $SUBDIR $OPTS $VARS $ARGS_QUOTED $TARGET
+  eval make -f \"$MAKEFILE\" $SUBDIR $OPTS $VARS $ARGS_QUOTED $TARGET
+  err_num=$?
+fi
+
+exit $err_num
